### ISSUE TITLE
Sending too many NULLS when copying from server

### ISSUE THREAD

**Issue by ghost** [Fabio286/neo-scp#1]
Hi, first of all I want to thank you for this awesome module. Without it I would probably still try to figure out how to get my files from the server.
But I noticed an issue: Often the files I downloaded where incomplete and I couldn't figure out why...until now.
Everytime data comes in you send a NULL to the server which of course you need to do but not when you receive the files in packages of 32 kB. This leads to the server thinking you've received all your files and it closes the connection.

To work around this problem you only need to send a NULL once before the filetransfer starts and once when you've received your file.

Kind regards.
masvarn

**Comment by Fabio286** [comment]
Hi masvarn,
Thanks for your report. I have to admit that i primarily used this module to upload files and i never noticed this issue in download.
I'll test and implement your solution, i really appreciate your advise.

Thanks again
Regard
